[env]
_.file = ["secrets.enc.yaml"]

[tools]
"go:go.abhg.dev/doc2go" = "0.12.0"

# [tasks.docs]
# description = "Generate documentation site"
# run = """
# rm -rf docs
# doc2go \
#     -C .. \
#     -out cfgate.io/docs/ \
#     -subdir assets \
#     ./...
# """

[tasks.pnpm]
description = "Run pnpm with Mise env"
run = "pnpm"
